/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#4edea3",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#97f5cc",
        "secondary": "#006c4e",
        "error": "#ba1a1a",
        "surface-tint": "#006c49",
        "primary": "#006c49",
        "surface-dim": "#d9dadb",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed": "#002113",
        "on-tertiary-fixed": "#002115",
        "primary-container": "#10b981",
        "tertiary-fixed-dim": "#a8cfbc",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#bbcabf",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "on-background": "#191c1d",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-container": "#00422b",
        "surface-container": "#edeeef",
        "on-primary": "#ffffff",
        "on-secondary-container": "#007353",
        "on-surface": "#191c1d",
        "on-error-container": "#93000a",
        "background": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "tertiary": "#416656",
        "on-error": "#ffffff",
        "outline": "#6c7a71",
        "on-secondary-fixed": "#002115",
        "on-surface-variant": "#3c4a42",
        "tertiary-fixed": "#c3ecd7",
        "tertiary-container": "#84ab98",
        "surface-variant": "#e1e3e4",
        "surface": "#f8f9fa",
        "secondary-fixed-dim": "#7bd8b1",
        "on-tertiary-container": "#1b3f31",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#00513a",
        "secondary-fixed": "#97f5cc",
        "on-primary-fixed-variant": "#005236",
        "surface-bright": "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#294e3f"
      },
      fontFamily: {
        "headline-2": ["Inter"],
        "button-text": ["Inter"],
        "caption": ["Inter"],
        "headline-1": ["Inter"],
        "body-main": ["Inter"]
      }
    },
  },
  plugins: [],
}
